version: '3.1'

services:
  postgres_strapi_blog:
    container_name: postgres_strapi_blog
    hostname: postgres_strapi_blog
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - C:\Users\gabri\OneDrive\Documentos\Programacao\Udemy\postgres_strapi_blog:/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432